apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: monitor-task-binding
spec:
  params:
  - name: pullrequesturl
    value: $(event.PullRequest.HTMLURL)

---

apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: monitor-task-template
spec:
  params:
  - name: pullrequesturl
    description: The pull request url
    type: string
  - name: gitsecretname
    description: The git secret name
    default: github-secrets
    type: string
  - name: gitsecretkeyname
    description: The git secret key name
    default: token
    type: string
  - name: commentsuccess
    description: The text of the success comment
    default: "Success"
    type: string
  - name: commentfailure
    description: The text of the failure comment
    default: "Failed"
    type: string
  - name: dashboardurl
    description: The URL to the pipelineruns page of the dashboard
    default: "http://localhost:9097/"
    type: string
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: pull-request-$(uid)
    spec:
      type: pullRequest
      params:
        - name: url
          value: $(params.pullrequesturl)
      secrets:
        - fieldName: githubToken
          secretName: $(params.gitsecretname)
          secretKey: $(params.gitsecretkeyname)
  - apiVersion: tekton.dev/v1alpha1
    kind: TaskRun
    metadata:
      generateName: monitor-taskrun-
    spec:
      taskRef:
        name: monitor-result-task
      inputs:
        params:
        - name: commentsuccess
          value: $(params.commentsuccess)
        - name: commentfailure
          value: $(params.commentfailure)
        - name: dashboard-url
          value: $(params.dashboardurl)
        - name: secret
          value: $(params.gitsecretname)
        resources:
        - name: pull-request
          resourceRef:
            name: pull-request-$(uid)